# vpnc config for bob — generated Sat Apr 18 09:54:20 WAT 2026
port      = 9000
server    = YOUR_SERVER_IP
ca_cert   = /home/cypherzona/VPN/myvpn/pki/ca/ca.crt
cli_cert  = /home/cypherzona/VPN/myvpn/pki/clients/bob/bob.crt
cli_key   = /home/cypherzona/VPN/myvpn/pki/clients/bob/bob.key
tun_ip    = 10.8.0.3/24
