port      = 9000
server    = 127.0.0.1
ca_cert   = ../../pki/ca/ca.crt
cli_cert  = ../../pki/clients/mubby/mubby.crt
cli_key   = ../../pki/clients/mubby/mubby.key
tun_ip    = 10.8.0.2/24
src/server/Makefile